package edu.csulb.cecs491b.studentnest.entity;

import lombok.Getter;

@Getter
public enum Department {
    // College of the Arts (COTA)
    BOB_CONSERVATORY_SCHOOL_OF_MUSIC("MUS"),
    DANCE("DANC"),
    DESIGN("DESN"),
    FILM_AND_ELECTRONIC_ARTS("FEA"),
    SCHOOL_OF_ART("ART"),
    THEATRE_ARTS("THA"),

    // College of Business (COB)
    ACCOUNTANCY("ACCT"),
    FINANCE("FIN"),
    HUMAN_RESOURCE_MANAGEMENT("HRM"),
    INFORMATION_SYSTEMS("INFS"),
    INTERNATIONAL_BUSINESS("IB"),
    LEGAL_BUSINESS_STUDIES("LBS"),
    MANAGEMENT("MGMT"),
    MARKETING("MKTG"),
    SUPPLY_CHAIN_MANAGEMENT("SCM"),

    // College of Education (CED)
    ADVANCED_STUDIES_IN_EDUCATION_AND_COUNSELING("ASEC"),
    EDUCATIONAL_LEADERSHIP("EDUL"),
    LIBERAL_STUDIES("LIBS"),
    TEACHER_EDUCATION("TEAD"),

    // College of Engineering (COE)
    BIOMEDICAL_ENGINEERING("BME"),
    CHEMICAL_ENGINEERING("CHE"),
    CIVIL_ENGINEERING_AND_CONSTRUCTION_MANAGEMENT("CECM"),
    COMPUTER_ENGINEERING_AND_COMPUTER_SCIENCE("CECS"),
    ELECTRICAL_ENGINEERING("EE"),
    MECHANICAL_AND_AEROSPACE_ENGINEERING("MAE"),

    // College of Health & Human Services (CHHS)
    FAMILY_AND_CONSUMER_SCIENCES("FCS"),
    HEALTH_CARE_ADMINISTRATION("HCA"),
    HEALTH_SCIENCE("HSCI"),
    KINESIOLOGY("KIN"),
    SCHOOL_OF_NURSING("NURS"),
    PHYSICAL_THERAPY("PT"),
    PUBLIC_POLICY_AND_ADMINISTRATION("PPA"),
    RECREATION_AND_LEISURE_STUDIES("REC"),
    SCHOOL_OF_CRIMINOLOGY_CRIMINAL_JUSTICE_AND_EMERGENCY_MANAGEMENT("CCJEM"),
    SCHOOL_OF_SOCIAL_WORK("SOCW"),
    SPEECH_LANGUAGE_PATHOLOGY("SLP"),

    // College of Liberal Arts (CLA)
    AFRICANA_STUDIES("AFRS"),
    AMERICAN_INDIAN_STUDIES("AIS"),
    AMERICAN_STUDIES("AMST"),
    ANTHROPOLOGY("ANTH"),
    ASLD("ASLD"),
    CHICANO_AND_LATINO_STUDIES("CHLS"),
    CLASSICS("CLSC"),
    COMMUNICATION_STUDIES("COMM"),
    COMPARATIVE_WORLD_LITERATURE("CWL"),
    ECONOMICS("ECON"),
    ENGLISH("ENGL"),
    ENVIRONMENTAL_SCIENCE_AND_POLICY("ESAP"),
    GEOGRAPHY("GEOG"),
    HISTORY("HIST"),
    HUMAN_DEVELOPMENT("HDEV"),
    INTERNATIONAL_STUDIES("INTS"),
    JEWISH_STUDIES("JWST"),
    JOURNALISM_AND_PUBLIC_RELATIONS("JOUR"),
    LATIN_AMERICA_STUDIES("LAS"),
    LEGAL_STUDIES("LST"),
    LINGUISTICS("LING"),
    PHILOSOPHY("PHIL"),
    POLITICAL_SCIENCE("POSC"),
    PSYCHOLOGY("PSY"),
    RELIGIOUS_STUDIES("RELS"),
    ROMANCE_GERMAN_RUSSIAN_LANGUAGES_AND_LITERATURES("RGRLL"),
    SOCIOLOGY("SOC"),
    WOMEN_GENDER_AND_SEXUALITY_STUDIES("WGSS"),

    // College of Natural Sciences & Mathematics (CNSM)
    BIOLOGICAL_SCIENCES("BIOL"),
    CHEMISTRY_AND_BIOCHEMISTRY("CHEM"),
    EARTH_SCIENCE("ERTH"),
    ENVIRONMENTAL_SCIENCE_AND_POLICY_CNSM("ES&P"),
    MATHEMATICS_AND_STATISTICS("MATH"),
    PHYSICS_AND_ASTRONOMY("PHYS"),
    SCIENCE_EDUCATION("SCED"),

    // College of Professional and Continuing Education (CPaCE)
    CERTIFICATIONS("CERT"),
    ONLINE_BACHELORS_DEGREE("OBD"),
    ONLINE_MASTERS_DEGREE("OMD"),
    PERSONAL_ENRICHMENT("PERS"),
    PROFESSIONAL_DESIGNATION("PDES"),
    PROFESSIONAL_DEVELOPMENT("PROD"),
    UNIVERSITY_CREDIT("UC");

    private final String abbreviation;

   Department(String abbreviation) {
        this.abbreviation = abbreviation;
    }

}
