package edu.csulb.cecs491b.studentnest.entity;

public enum Major {
    COMPUTER_SCIENCE,
    SOFTWARE_ENGINEERING,
    INFORMATION_SYSTEMS,
    ELECTRICAL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    BUSINESS,
    UNDECLARED
}
