spring:
  datasource:
    url: jdbc:mysql://puggu.dev:3306/student_nest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: Developer
    password: 2025_StudentNest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080
