spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_nest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: student_user
    password: StrongPass123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080
